version: "3.8"

services:
  nginx:
    image: nginx:1.19
    ports:
    - "8080:80"
    volumes:
    - ./src:/src
    - ./vhost.conf:/etc/nginx/conf.d/default.conf
    networks:
      www:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ./src:/src
    networks:
      www:

networks:
  www:
